/*
 * Carsten Langgaard, carstenl@mips.com
 * Copyright (C) 2000 MIPS Technologies, Inc.  All rights reserved.
 *
 * ########################################################################
 *
 *  This program is free software; you can distribute it and/or modify it
 *  under the terms of the GNU General Public License (Version 2) as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
 *
 * ########################################################################
 *
 * Defines of the Jupiter board specific address-MAP, registers, etc.
 *
 */
#ifndef _MACH_JUPITER_H
#define _MACH_JUPITER_H

#include <asm/addrspace.h>
#include <venus.h>



/*-------------------------------------------------------------
 * Jupiter ISO
 *-------------------------------------------------------------*/
#define JUPITER_ISO_BASE			(KSEG1 + VENUS_IO_PORT_BASE)

/*
 * Jupiter ISO SYS registers.
 */
#define OFFSET_JUPITER_ISO_ISR			0xBD00
#define OFFSET_JUPITER_ISO_UMSK_ISR		0xBD04
#define OFFSET_JUPITER_ISO_UMSK_ISR_GP		0xBD08
#define OFFSET_JUPITER_ISO_UMSK_ISR_KPADAH	0xBD0C
#define OFFSET_JUPITER_ISO_UMSK_ISR_KPADAL	0xBD10
#define OFFSET_JUPITER_ISO_UMSK_ISR_KPADDAH	0xBD14
#define OFFSET_JUPITER_ISO_UMSK_ISR_KPADDAL	0xBD18
#define OFFSET_JUPITER_ISO_UMSK_ISR_SW		0xBD1C
#define OFFSET_JUPITER_ISO_DBG			0xBD20
#define OFFSET_JUPITER_ISO_DUMMY		0XBD24
#define OFFSET_JUPITER_ISO_CHIP_INFO1		0xBD28
#define OFFSET_JUPITER_ISO_CHIP_INFO2		0xBD2C
#define OFFSET_JUPITER_ISO_CHIP_CTRL		0xBD30
#define OFFSET_JUPITER_ISO_RTC			0xBD34
#define OFFSET_JUPITER_ISO_CELL			0xBD38
#define OFFSET_JUPITER_ISO_POWER		0xBD3C
#define JUPITER_ISO_ISR				(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_ISR)
#define JUPITER_ISO_UMSK_ISR			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_UMSK_ISR)
#define JUPITER_ISO_UMSK_ISR_GP			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_UMSK_ISR_GP)
#define JUPITER_ISO_UMSK_ISR_KPADAH		(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_UMSK_ISR_KPADAH)
#define JUPITER_ISO_UMSK_ISR_KPADAL		(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_UMSK_ISR_KPADAL)
#define JUPITER_ISO_UMSK_ISR_KPADDAH		(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_UMSK_ISR_KPADDAH)
#define JUPITER_ISO_UMSK_ISR_KPADDAL		(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_UMSK_ISR_KPADDAL)
#define JUPITER_ISO_UMSK_ISR_SW			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_UMSK_ISR_SW)
#define JUPITER_ISO_DBG				(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_DBG)
#define JUPITER_ISO_DUMMY			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_DUMMY)
#define JUPITER_ISO_CHIP_INFO1			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_CHIP_INFO1)
#define JUPITER_ISO_CHIP_INFO2			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_CHIP_INFO2)
#define JUPITER_ISO_CHIP_CTRL			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_CHIP_CTRL)
#define JUPITER_ISO_RTC				(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_RTC)
#define JUPITER_ISO_CELL			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_CELL)
#define JUPITER_ISO_POWER			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_POWER)


/*
 * Jupiter ISO GPIO registers.
 */
#define OFFSET_JUPITER_ISO_GPDIR		0xBD70
#define OFFSET_JUPITER_ISO_GPDATO		0xBD74
#define OFFSET_JUPITER_ISO_GPDATI		0xBD78
#define OFFSET_JUPITER_ISO_GPIE			0xBD7C
#define OFFSET_JUPITER_ISO_GPDP			0xBD80
#define OFFSET_JUPITER_ISO_GPDEB		0xBD84
#define JUPITER_ISO_GPDIR			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_GPDIR)
#define JUPITER_ISO_GPDATO			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_GPDATO)
#define JUPITER_ISO_GPDATI			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_GPDATI)
#define JUPITER_ISO_GPIE			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_GPIE) 
#define JUPITER_ISO_GPDP			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_GPDP)
#define JUPITER_ISO_GPDEB			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_GPDEB)


/*
 * Jupiter ISO IrDA registers.
 */
#define OFFSET_JUPITER_ISO_IR_PSR		0xBE00
#define OFFSET_JUPITER_ISO_IR_PRE		0xBE04
#define OFFSET_JUPITER_ISO_IR_SF		0xBE08
#define OFFSET_JUPITER_ISO_IR_DPIR		0xBE0C
#define OFFSET_JUPITER_ISO_IR_CR		0xBE10
#define OFFSET_JUPITER_ISO_IR_RP		0xBE14
#define OFFSET_JUPITER_ISO_IR_SR		0xBE18
#define JUPITER_ISO_IR_PSR			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_IR_PSR)
#define JUPITER_ISO_IR_PRE			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_IR_PRE)
#define JUPITER_ISO_IR_SF			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_IR_SF)
#define JUPITER_ISO_IR_DPIR			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_IR_DPIR)
#define JUPITER_ISO_IR_CR			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_IR_CR)
#define JUPITER_ISO_IR_RP			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_IR_RP)
#define JUPITER_ISO_IR_SR			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_IR_SR)


/*
 * Jupiter ISO DRM registers.
 */
#define OFFSET_JUPITER_ISO_DRM_ST		0xBF00
#define OFFSET_JUPITER_ISO_DRM_SECURE_CLK	0xBF04
#define OFFSET_JUPITER_ISO_DRM_ELAPSED		0xBF08
#define OFFSET_JUPITER_ISO_COLD_RST		0xBF0C
#define OFFSET_JUPITER_ISO_COLD_RST1		0xBF10
#define OFFSET_JUPITER_ISO_COLD_RST2		0xBF14
#define JUPITER_ISO_DRM_ST			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_DRM_ST)
#define JUPITER_ISO_DRM_SECURE_CLK		(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_DRM_SECURE_CLK)
#define JUPITER_ISO_DRM_ELAPSED			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_DRM_ELAPSED)
#define JUPITER_ISO_COLD_RST			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_COLD_RST)
#define JUPITER_ISO_COLD_RST1			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_COLD_RST1)
#define JUPITER_ISO_COLD_RST2			(JUPITER_ISO_BASE + OFFSET_JUPITER_ISO_COLD_RST2)


/*-------------------------------------------------------------
 * Jupiter SB2
 *-------------------------------------------------------------*/
#define JUPITER_SB2_BASE			(KSEG1 + VENUS_IO_PORT_BASE)

/*
 * Jupiter SB2 dummy registers.
 */
#define OFFSET_JUPITER_SB2_DUMMY_0		0xA600
#define OFFSET_JUPITER_SB2_DUMMY_1		0xA604
#define OFFSET_JUPITER_SB2_DUMMY_2		0xA608
#define OFFSET_JUPITER_SB2_DUMMY_3		0xA60C
#define JUPITER_SB2_DUMMY_0			(JUPITER_SB2_BASE + OFFSET_JUPITER_SB2_DUMMY_0)
#define JUPITER_SB2_DUMMY_1			(JUPITER_SB2_BASE + OFFSET_JUPITER_SB2_DUMMY_1)
#define JUPITER_SB2_DUMMY_2			(JUPITER_SB2_BASE + OFFSET_JUPITER_SB2_DUMMY_2)
#define JUPITER_SB2_DUMMY_3			(JUPITER_SB2_BASE + OFFSET_JUPITER_SB2_DUMMY_3)
#define JUPITER_SW_MUTEX_RESET			JUPITER_SB2_DUMMY_0
#define JUPITER_SW_MUTEX_DC			JUPITER_SB2_DUMMY_1


/*-------------------------------------------------------------
 * Jupiter CRT
 *-------------------------------------------------------------*/
#define JUPITER_CRT_BASE			(KSEG1 + 0x18000000)

/*
 * Jupiter CRT pad mux registers.
 */
#define OFFSET_JUPITER_CRT_MUXPAD_0		0x350
#define OFFSET_JUPITER_CRT_MUXPAD_1		0x354
#define OFFSET_JUPITER_CRT_MUXPAD_2		0x358
#define OFFSET_JUPITER_CRT_MUXPAD_3		0x35c
#define OFFSET_JUPITER_CRT_MUXPAD_4		0x360
#define OFFSET_JUPITER_CRT_MUXPAD_5		0x364
#define OFFSET_JUPITER_CRT_MUXPAD_6		0x368
#define OFFSET_JUPITER_CRT_MUXPAD_7		0x36c
#define OFFSET_JUPITER_CRT_MUXPAD_8		0x370
#define OFFSET_JUPITER_CRT_MUXPAD_9		0x374
#define OFFSET_JUPITER_CRT_MUXPAD_10		0x378
#define OFFSET_JUPITER_CRT_MUXPAD_11		0x37c
#define OFFSET_JUPITER_CRT_MUXPAD_12		0x380
#define JUPITER_CRT_MUXPAD_0			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_0)
#define JUPITER_CRT_MUXPAD_1			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_1)
#define JUPITER_CRT_MUXPAD_2			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_2)
#define JUPITER_CRT_MUXPAD_3			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_3)
#define JUPITER_CRT_MUXPAD_4			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_4)
#define JUPITER_CRT_MUXPAD_5			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_5)
#define JUPITER_CRT_MUXPAD_6			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_6)
#define JUPITER_CRT_MUXPAD_7			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_7)
#define JUPITER_CRT_MUXPAD_8			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_8)
#define JUPITER_CRT_MUXPAD_9			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_9)
#define JUPITER_CRT_MUXPAD_10			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_10)
#define JUPITER_CRT_MUXPAD_11			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_11)
#define JUPITER_CRT_MUXPAD_12			(JUPITER_CRT_BASE + OFFSET_JUPITER_CRT_MUXPAD_12)

#define JUPITER_MUXPAD_0			((volatile unsigned int *)JUPITER_CRT_MUXPAD_0)
#define JUPITER_MUXPAD_1			((volatile unsigned int *)JUPITER_CRT_MUXPAD_1)
#define JUPITER_MUXPAD_2			((volatile unsigned int *)JUPITER_CRT_MUXPAD_2)
#define JUPITER_MUXPAD_3			((volatile unsigned int *)JUPITER_CRT_MUXPAD_3)
#define JUPITER_MUXPAD_4			((volatile unsigned int *)JUPITER_CRT_MUXPAD_4)
#define JUPITER_MUXPAD_5			((volatile unsigned int *)JUPITER_CRT_MUXPAD_5)
#define JUPITER_MUXPAD_6			((volatile unsigned int *)JUPITER_CRT_MUXPAD_6)
#define JUPITER_MUXPAD_7			((volatile unsigned int *)JUPITER_CRT_MUXPAD_7)
#define JUPITER_MUXPAD_8			((volatile unsigned int *)JUPITER_CRT_MUXPAD_8)
#define JUPITER_MUXPAD_9			((volatile unsigned int *)JUPITER_CRT_MUXPAD_9)
#define JUPITER_MUXPAD_10			((volatile unsigned int *)JUPITER_CRT_MUXPAD_10)
#define JUPITER_MUXPAD_11			((volatile unsigned int *)JUPITER_CRT_MUXPAD_11)
#define JUPITER_MUXPAD_12			((volatile unsigned int *)JUPITER_CRT_MUXPAD_12)


#endif /* !(_MACH_JUPITER_H) */

