#!/bin/bash

intf_usb()
{
	sed -i '/CONFIG_USB_HCI = /c\CONFIG_USB_HCI = y' Makefile
	sed -i '/CONFIG_PCI_HCI = /c\CONFIG_PCI_HCI = n' Makefile
	sed -i '/CONFIG_SDIO_HCI = /c\CONFIG_SDIO_HCI = n' Makefile
}
intf_pcie()
{
	sed -i '/CONFIG_USB_HCI = /c\CONFIG_USB_HCI = n' Makefile
	sed -i '/CONFIG_PCI_HCI = /c\CONFIG_PCI_HCI = y' Makefile
	sed -i '/CONFIG_SDIO_HCI = /c\CONFIG_SDIO_HCI = n' Makefile
}
intf_sdio()
{
	sed -i '/CONFIG_USB_HCI = /c\CONFIG_USB_HCI = n' Makefile
	sed -i '/CONFIG_PCI_HCI = /c\CONFIG_PCI_HCI = n' Makefile
	sed -i '/CONFIG_SDIO_HCI = /c\CONFIG_SDIO_HCI = y' Makefile
}

nic_8192c()
{
	sed -i '/CONFIG_RTL8192C = /c\CONFIG_RTL8192C = y' Makefile
	sed -i '/CONFIG_RTL8192D = /c\CONFIG_RTL8192D = n' Makefile
}
nic_8192d()
{
	sed -i '/CONFIG_RTL8192C = /c\CONFIG_RTL8192C = n' Makefile
	sed -i '/CONFIG_RTL8192D = /c\CONFIG_RTL8192D = y' Makefile
}

release_92cu()
{
	HCI="usb"
	CHIP="rtl8192c"

	nic_8192c
	intf_usb

	make_common_dir
	copy_common_file
}

release_92ce()
{
	HCI="pci"
	CHIP="rtl8192c"

	nic_8192c
	intf_pcie

	make_common_dir
	copy_common_file
}

release_92du()
{
	HCI="usb"
	CHIP="rtl8192d"

	nic_8192d
	intf_usb

	make_common_dir
	copy_common_file
}

make_common_dir()
{
	mkdir $folder
	mkdir $folder/core
	mkdir $folder/core/efuse
	mkdir $folder/hal
	mkdir $folder/hal/$CHIP/
	mkdir $folder/hal/$CHIP/$HCI
	mkdir $folder/include
	mkdir $folder/include/byteorder
	mkdir $folder/os_dep
	mkdir $folder/os_dep/linux
}

add_version_file()
{
	defversion="#define DRIVERVERSION\t\"$postfix\""
	echo -e $defversion > include/rtw_version.h
}

copy_common_file()
{
	cp Makefile $folder/Makefile

	cp script/wlan0dhcp $folder/.
	cp script/ifcfg-wlan0 $folder/.
	cp script/wpa1.conf $folder/.
	cp script/runwpa $folder/.
	cp script/clean $folder/.

	add_version_file
	cp -fr include/ $folder/.
	
	cp core/*.c $folder/core
	cp core/efuse/rtw_efuse.c $folder/core/efuse/.

	cp hal/hal_init.c $folder/hal/.

	cp hal/$CHIP/*.c $folder/hal/$CHIP
	cp hal/$CHIP/$HCI/*.c $folder/hal/$CHIP/$HCI

	cp os_dep/osdep_service.c $folder/os_dep/.
	cp os_dep/linux/*.c $folder/os_dep/linux

	cp $IA autoconf_$CHIP"_"$HCI"_"linux.h $folder/include/autoconf.h
	cp $IA autoconf_$CHIP"_"$HCI"_"linux.h $folder/.
}

clean_old()
{
	rm -fr $folder
	rm -fr $folder.tar.gz
}

clean_folder()
{
	rm -rf $folder/.svn
	rm -rf $folder/include/.svn
	rm -rf $folder/include/byteorder/.svn	

	rm -rf $folder/core/.svn
	rm -rf $folder/core/efuse/.svn
	
	rm -rf $folder/hal/.svn
	rm -rf $folder/hal/$CHIP/.svn
	rm -rf $folder/hal/$CHIP/$HCI/.svn

	rm -rf $folder/os_dep/.svn
	rm -rf $folder/os_dep/linux/.svn	
}

zip_folder()
{
	tar -zcvf $folder.tar.gz $folder/
	#tar -zcvf $folder.tar.gz $folder/  > /dev/null 2>&1
	#rm -fr $folder
}

package()
{
	clean_folder
	zip_folder
}

get_svn_revision()
{
	svn_rev=`svn info | sed -n 's/^Revision: *\([0-9][0-9]*\)/\1/p'`
	if [ -z "$svn_rev" ]; then
		svn_rev=`svn info | sed -n 's/^­׭qª©: *\([0-9][0-9]*\)/\1/p'`
	fi
	if [ -z "$svn_rev" ] && [ -f .svn/entries ]; then
		svn_rev=`sed -n '4s/^\([0-9][0-9]*\)$/\1/p' < .svn/entries`
	fi
	if [ -z "$svn_rev" ]; then
		svn_rev="xxxx"
	fi
}


#==========================
# Script Start From Here

# set variables
# interactive
IA=""
# target folder
folder92cu="rtl8192_8188CU_linux"
folder92ce="rtl8192_8188CE_linux"
folder92du="rtl8192_8188DU_linux"

# Select NIC type
if [ -z "$1" ]; then
	IA="-i"
	echo "Please select interface type(1/2/3):"
	select card in RTL8192cu RTL8192ce RTL8192du;
	do
		echo "You have selected $card"
		break
	done
else
	card=$1;
fi

# Make Version string
if [ -z "$2" ]; then
	get_svn_revision
	version="v3.0."$svn_rev
	datestr=$(date +%Y%m%d)
	postfix=$version.$datestr
else
	postfix=$2
fi

# Make
case "$card" in
	[Rr][Tt][Ll][8][1][9][2][Cc][Uu])
		folder=$folder92cu"_"$postfix
		clean_old
		release_92cu
		package
		;;
	[Rr][Tt][Ll][8][1][9][2][Cc][Ee])
		folder=$folder92ce"_"$postfix
		clean_old
		release_92ce
		package
		;;
	[Rr][Tt][Ll][8][1][9][2][Dd][Uu])
		folder=$folder92du"_"$postfix
		clean_old
		release_92du
		package
		;;
	*)
		echo "Unknown NIC type"
		;;
esac
