
# for version 3
RTL8192CE_DRV := $(shell $(src)/checkout_source $(src)/../../combo/rtl8192c_8192d $(src)/drv/)
#RTL8192CE_DRV := $(shell rm -rf $(src)/drv/; cp $(src)/v1/ $(src)/drv/ -rf;)

obj-m       += drv/
